export const LEGENDARY_CARDS = Object.freeze({
  legendaryUnlimitedTorchGauge: Object.freeze({
    id: "legendary_unlimited_torch_gauge",
    rarity: "L",
    cost: 6,
    name: "UNLIMITED TORCH GAUGE",
    footerText: "UNLIMITED TORCH GAUGE",
    nameJa: "たいまつゲージ無制限",
    category: "exploration",
    iconId: "torch",
    effectId: "unlimited_torch_gauge",
    maxCopies: 1,
    version: 2,
  }),
  legendaryAbilityBoostPlus: Object.freeze({
    id: "legendary_ability_boost_plus",
    rarity: "L",
    cost: 6,
    name: "Ability Boost +",
    footerText: "ALL ABILITIES +5",
    nameJa: "能力向上＋",
    concept: "STR / INT / AGI / DEX / LUC +5",
    category: "ability",
    iconId: "power-pose",
    effectId: "all_ability_up_plus",
    effectValue: 5,
    statBonus: Object.freeze({ str: 5, int: 5, agi: 5, dex: 5, luc: 5 }),
    maxOwned: 99,
    maxCopies: 6,
    version: 1,
  }),
});
