import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';import vm from 'node:vm';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const previous=await readFile('tests/browser/special-map-v2-f1-outcomes.mjs','utf8'),scope={};vm.runInNewContext(previous.slice(previous.indexOf('const baseHook='),previous.indexOf('\nconst main='))+';this.hook=baseHook;',scope);
const main=await readFile('js/main.js','utf8'),title=await readFile('js/title-screen.js','utf8');
const extra=`window.stairQa={set(type,portal=null){closeTown();worldLocation='dungeon';currentDepth=portal?Number(portal.match(/b([0-9]+)f/)[1]):1;say(type==='stairsDown'?'下り階段':'出口・転送門');state.anim=null;state.overlayEvent={type:'stairsPrompt',cellType:type};cells[state.gridY][state.gridX].type=type;cells[state.gridY][state.gridX].portal=portal;updateHud();},event(type){state.overlayEvent=type?{type}:null;updateHud();},map(){currentDepth=10;state.minimapBlocked=false;state.torchFuel=100;toggleMinimapOverlay();updateHud();}};`;
await mkdir('artifacts/dungeon-stairs',{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});
try{for(const width of [1280,390]){const p=await browser.newPage({viewport:{width,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/js/main.js?*',r=>r.fulfill({contentType:'text/javascript',body:main.replace('  document.documentElement.dataset.ndaMainReady = "true";',scope.hook+extra+' document.documentElement.dataset.ndaMainReady = "true";')}));await p.route('**/js/title-screen.js?*',r=>r.fulfill({contentType:'text/javascript',body:title+'\ntitleOpen=false;'}));await p.goto('http://127.0.0.1:4177');await p.waitForFunction(()=>window.stairQa);await p.evaluate(()=>v2Qa.setup());
for(const [type,portal,file] of [['stairsUp',null,'exit'],['stairsDown',null,'down_stairs'],['stairsUp','transfer_b10f','transport_portal'],['stairsUp','transfer_b100f','transport_portal']]){await p.evaluate(([t,p])=>stairQa.set(t,p),[type,portal]);const img=p.locator('.dungeon-stair-image');await img.waitFor({state:'visible'});await p.waitForFunction(file=>{const i=document.querySelector('.dungeon-stair-image');return i.src.endsWith('/'+file+'.avif')&&i.complete&&i.naturalWidth>0;},file);assert.match(await img.evaluate(i=>getComputedStyle(i).filter),/drop-shadow/);await p.screenshot({path:`artifacts/dungeon-stairs/${width}-${portal||file}.png`});await p.evaluate(()=>stairQa.event('npcTalk'));await img.waitFor({state:'hidden'});await p.evaluate(()=>stairQa.event(null));await img.waitFor({state:'visible'});}
await p.evaluate(()=>stairQa.map());await p.locator('.dungeon-stair-image').waitFor({state:'hidden'});await p.evaluate(()=>stairQa.map());await p.locator('.dungeon-stair-image').waitFor({state:'visible'});assert.deepEqual(errors,[]);console.log(width,'passed');await p.close();}}finally{await browser.close();}
