import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');
const main=await readFile('js/main.js','utf8');
const hook=`window.gqa={setup:()=>{document.querySelector('#titleScreen').hidden=true;document.body.classList.remove('title-active','menu-open');closeTown();worldLocation='dungeon';currentDepth=31;firstDungeonTutorialActive=false;deckTutorialActive=false;character=createInitialCharacter({name:'スピネル',job:'thief'});character.eventFlags={gemini_first_completed:true};setBgmOptions({enabled:false});setSeOptions({enabled:false});updateCharacterUi();},character:()=>character};`;
await mkdir('artifacts/gemini-second',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
try {for(const [label,width,height] of [['pc',1280,900],['mobile',390,844]]) {
 const page=await browser.newPage({viewport:{width,height}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/js/main.js?*',r=>r.fulfill({contentType:'text/javascript',body:main.replace('  document.documentElement.dataset.ndaMainReady = "true";',hook+'\n  document.documentElement.dataset.ndaMainReady = "true";')}));
 await page.goto('http://127.0.0.1:4179');await page.waitForFunction(()=>window.gqa);
 await page.evaluate(async()=>{gqa.setup();window.gplayer=await import('/js/player.js');gplayer.startGeminiSecondEvent(1,1);});
 await page.waitForTimeout(1900);await page.screenshot({path:`artifacts/gemini-second/${label}-sisters.png`});
 await page.evaluate(()=>gplayer.handleOverlayEventInput('confirm'));
 assert.ok((await page.locator('#message').textContent()).includes('地下40階'));
 await page.screenshot({path:`artifacts/gemini-second/${label}-hint.png`});
 await page.evaluate(()=>gplayer.handleOverlayEventInput('confirm'));
 await page.waitForFunction(()=>gplayer.state.overlayEvent.phase==='gone');
 assert.equal(await page.evaluate(()=>gqa.character().eventFlags.gemini_second_completed),true);
 await page.screenshot({path:`artifacts/gemini-second/${label}-gone.png`});
 await page.evaluate(()=>gplayer.startGeminiSecondEvent(1,1));
 assert.ok((await page.locator('#message').textContent()).includes('反芻'));
 await page.screenshot({path:`artifacts/gemini-second/${label}-reminder.png`});
 await page.evaluate(()=>{gqa.character().eventFlags={gemini_retry_variant:true};gplayer.startGeminiEvent(1,1);});
 await page.waitForTimeout(500);await page.screenshot({path:`artifacts/gemini-second/${label}-retry.png`});
 await page.evaluate(()=>{for(let i=0;i<4;i++)gplayer.handleOverlayEventInput('confirm');});
 assert.ok((await page.locator('#message').textContent()).includes('Aボタン：月の箱'));
 await page.evaluate(()=>gplayer.handleOverlayEventInput('confirm'));
 await page.waitForFunction(()=>gplayer.state.overlayEvent.phase==='opened');
 await page.evaluate(()=>gplayer.handleOverlayEventInput('confirm'));
 assert.equal(await page.evaluate(()=>gqa.character().eventFlags.gemini_first_completed),true);
 assert.equal(await page.locator('#itemGetEffect').isVisible(),true);
 assert.deepEqual(errors,[]);console.log(label+' second act, reminder and moon retry passed');await page.close();
}}finally{await browser.close();}
