import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createRequire} from 'node:module';import vm from 'node:vm';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('playwright');const output=process.env.NDA_BETA_OUTPUT||'artifacts/map-beta';await mkdir(output,{recursive:true});
const old=await readFile('tests/browser/special-map-v2-f1-outcomes.mjs','utf8'),scope={};vm.runInNewContext(old.slice(old.indexOf('const baseHook='),old.indexOf('\nconst main='))+';this.hook=baseHook;',scope);
const extra=`window.betaQa={
 c:()=>character, event:()=>state.overlayEvent,
 async init(){await v2Qa.setup();(await import('/js/explorer-preview.js')).setExplorerTestEnabled(false);character.specialMaps=(await import('/data/special-maps.js')).normalizeSpecialMaps();delete character.trelirenProgress;delete character.eventFlags.treliren_met;character.highestDungeonDepthReached=10;character.lootBagTutorialSeen=true;
 for(const r of (await import('/data/tavern-rumors.js')).TAVERN_RUMORS)if(r.id!=='rumor_019')for(const p of r.phases)character.eventFlags[p.readFlag]=true;this.town('dungeon');saveGame();},
 town(id){closeTown();worldLocation='town';openTown({registrationRequired:false,facilityId:id,mode:id==='dungeon'?'dungeonEntrance':'facilityMenu'});updateCharacterUi();},
 meet(fresh=true){closeTown();worldLocation='dungeon';if(fresh)character.trelirenRun=normalizeTrelirenRun();beginTrelirenEncounter('qa-instance');},
 input:handleOverlayEventInput,gamepad:dispatchGamepadAction,
 resume(){document.querySelector('#titleScreen').hidden=true;document.body.classList.remove('title-active');window.dispatchEvent(new Event('nda:continue'));},
 failSave(on){if(!this.original)this.original=Storage.prototype.setItem;const orig=this.original;Storage.prototype.setItem=on?function(k,v){if(k==='nda.save.slot1.current')throw Error('QA quota');return orig.call(this,k,v);}:orig;},
 debug:async()=>(await import('/js/explorer-preview.js')).isExplorerTestEnabled()
};`;
const main=await readFile('js/main.js','utf8'),title=await readFile('js/title-screen.js','utf8');const browser=await chromium.launch({channel:'msedge',headless:true}),results=[];
try{for(const width of [1280,390]){const p=await browser.newPage({viewport:{width,height:900},hasTouch:width===390}),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message);});p.setDefaultTimeout(30000);
await p.route('**/js/main.js?*',r=>r.fulfill({contentType:'text/javascript',body:main.replace('  document.documentElement.dataset.ndaMainReady = "true";',scope.hook+extra+' document.documentElement.dataset.ndaMainReady = "true";')}));await p.route('**/js/title-screen.js?*',r=>r.fulfill({contentType:'text/javascript',body:title+'\ntitleOpen=false;'}));
await p.goto('http://127.0.0.1:4177');await p.waitForFunction(()=>window.betaQa);await p.evaluate(()=>betaQa.init());assert.equal(await p.locator('[data-entrance-command="explorerTent"]').isDisabled(),true);
for(let n=1;n<=3;n++){console.log(width,'meeting',n);await p.evaluate(()=>betaQa.meet());
 if(n===3){assert.equal(await p.evaluate(()=>betaQa.c().trelirenRun.phase),5);assert.equal(await p.evaluate(()=>betaQa.c().trelirenRun.rewardGiven),false);for(let i=0;i<130;i++){if(await p.evaluate(()=>betaQa.c().trelirenRun.phase===5))break;await p.evaluate(()=>betaQa.input('confirm'));await p.waitForTimeout(80);}assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.encounters),2);await p.evaluate(()=>betaQa.input('confirm'));await p.screenshot({path:output+'/'+width+'-request.png'});
 const encounterId=await p.evaluate(()=>betaQa.c().trelirenRun.encounterId);await p.evaluate(()=>betaQa.input('cancel'));assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.requestCompleted),false);await p.evaluate(()=>betaQa.meet(false));assert.equal(await p.evaluate(()=>betaQa.c().trelirenRun.encounterId),encounterId);
 for(let i=0;i<100;i++){if(await p.evaluate(()=>betaQa.c().trelirenRun.phase===5))break;await p.evaluate(()=>betaQa.input('confirm'));await p.waitForTimeout(80);}
 assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.encounters),2);
 await p.reload();await p.waitForFunction(()=>window.betaQa);await p.evaluate(()=>betaQa.resume());await p.waitForFunction(()=>betaQa.event()?.type==='trelirenTalk');assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.encounters),2);}
 for(let i=0;i<150;i++){if(await p.evaluate(()=>betaQa.c().trelirenRun.encountered))break;await p.evaluate(()=>betaQa.input('confirm'));await p.waitForTimeout(80);}assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.encounters),n);
}
assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.requestCompleted),true);
await p.evaluate(()=>betaQa.meet());assert.equal(await p.evaluate(()=>betaQa.c().trelirenRun.phase),6);assert.match(await p.evaluate(()=>betaQa.event().typing.characters.join('')),/いつでもいいから/);await p.evaluate(()=>betaQa.input('confirm'));await p.screenshot({path:output+'/'+width+'-fourth.png'});
for(let i=0;i<60;i++){if(await p.evaluate(()=>betaQa.c().trelirenRun.encountered))break;await p.evaluate(()=>betaQa.input('confirm'));await p.waitForTimeout(80);}assert.equal(await p.evaluate(()=>betaQa.c().trelirenProgress.encounters),4);
await p.evaluate(()=>betaQa.town('dungeon'));assert.equal(await p.locator('[data-entrance-command="explorerTent"]').isDisabled(),true);
await p.evaluate(()=>betaQa.town('tavern'));await p.getByRole('button',{name:'噂話',exact:true}).dispatchEvent('click');await p.waitForTimeout(100);await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>Boolean(betaQa.c().eventFlags.tavern_rumor_019_base_read)),false);
for(let i=0;i<25;i++){if(await p.evaluate(()=>betaQa.c().eventFlags.tavern_rumor_019_base_read))break;await p.evaluate(()=>betaQa.gamepad('confirm'));await p.waitForTimeout(80);}assert.equal(await p.evaluate(()=>betaQa.c().eventFlags.tavern_rumor_019_base_read),true);
await p.evaluate(()=>betaQa.town('dungeon'));assert.equal(await p.locator('[data-entrance-command="explorerTent"]').isEnabled(),true);assert.equal(await p.locator('[data-entrance-command="mapExploration"]').isDisabled(),true);await p.screenshot({path:output+'/'+width+'-entrance-locked.png'});
await p.locator('[data-entrance-command="explorerTent"]').dispatchEvent('click');await p.getByRole('textbox',{name:'地図署名',exact:true}).fill('スピネ');await p.getByRole('textbox',{name:'地図署名',exact:true}).press('Enter');if(!await p.evaluate(()=>betaQa.c().specialMaps.discovererName))await p.getByRole('textbox',{name:'地図署名',exact:true}).press('Enter');
const next=()=>p.getByRole('button',{name:'次へ（A）',exact:true});
for(let i=0;i<30;i++){if(await p.evaluate(()=>betaQa.c().specialMaps.starterMapsGranted))break;if(width===390)await next().tap();else await p.keyboard.press('Enter');await p.waitForTimeout(90);}assert.equal(await p.evaluate(()=>betaQa.c().specialMaps.unidentified.length),3);
await p.locator('#itemGetEffect:not([hidden])').waitFor({state:'visible'});assert.match(await p.locator('#itemGetItems').textContent(),/「はじまりの白地図」（3枚）を\n受け取った！/);await p.waitForTimeout(1100);await p.screenshot({path:output+'/'+width+'-starter.png'});await p.locator('#itemGetEffect').waitFor({state:'hidden'});
await p.reload();await p.waitForFunction(()=>window.betaQa);await p.evaluate(()=>betaQa.resume());await p.waitForFunction(()=>betaQa.c());await p.locator('[data-entrance-command="explorerTent"]').dispatchEvent('click');
assert.equal(await p.evaluate(()=>betaQa.c().specialMaps.unidentified.length),3);
for(let i=0;i<80;i++){if(await p.evaluate(()=>betaQa.c().specialMaps.betaExplanationComplete))break;if(width===390)await next().tap();else await p.evaluate(()=>betaQa.gamepad('confirm'));await p.waitForTimeout(90);}assert.equal(await p.evaluate(()=>betaQa.c().specialMaps.betaExplanationComplete),true);
await p.getByRole('button',{name:'はじまりの白地図 1',exact:true}).click();await p.getByRole('button',{name:'はじまりの白地図 1',exact:true}).click();for(let i=0;i<3;i++)await p.getByRole('button',{name:'確認（A）',exact:true}).click();assert.equal(await p.evaluate(()=>betaQa.c().specialMaps.betaExplorationUnlocked),true);
await p.getByRole('button',{name:'戻る（B）',exact:true}).click();await p.getByRole('button',{name:'戻る（B）',exact:true}).click();await p.getByRole('button',{name:'戻る',exact:true}).dispatchEvent('click');assert.equal(await p.locator('[data-entrance-command="mapExploration"]').isEnabled(),true);assert.equal(await p.evaluate(()=>betaQa.debug()),false);await p.screenshot({path:output+'/'+width+'-entrance-unlocked.png'});
await p.locator('[data-entrance-command="mapExploration"]').dispatchEvent('click');const map=p.getByRole('button',{name:/の地図 Lv\./}).first();await map.click();await map.click();await p.getByRole('button',{name:'探索する（A）',exact:true}).click();await p.getByRole('button',{name:'はい（A／ENTER）',exact:true}).click();await p.waitForFunction(()=>v2Qa.s()&&!v2Qa.s().transitioning);assert.equal(await p.evaluate(()=>betaQa.debug()),false);await p.screenshot({path:output+'/'+width+'-exploration.png'});assert.deepEqual(errors,[]);results.push({width,meetings:4,requestAtStart:true,fourthFollowup:true,requestReload:true,rumorGate:true,starterCount:3,explanationReload:true,firstAppraisalUnlock:true,debug:false});await p.close();}}
finally{await writeFile(output+'/introduction.json',JSON.stringify(results,null,2));await browser.close();}
