const BUILTIN_DEFAULTS=Object.freeze({normal:"vanish_default",undead:"vanish_ash",spirit:"vanish_evaporate",slime:"vanish_dissolve",construct:"vanish_shatter",boss:"vanish_boss"});
const BUILTIN_EFFECT=Object.freeze({id:"vanish_default",name:"Default Fade",duration:650,seed:1,steps:Object.freeze([{id:"fade_1",type:"fade",enabled:true,start:0,duration:650,from:1,to:0}])});
let catalog={format:"NDA_VANISH_EFFECTS",version:1,defaults:{...BUILTIN_DEFAULTS},effects:{vanish_default:BUILTIN_EFFECT}};
const activePlaybacks=new Set();
const maskBuffers=new WeakMap();
const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
const asNumber=(value,fallback=0)=>{if(value&&typeof value==="object"){const min=Number(value.min),max=Number(value.max);if(Number.isFinite(min)&&Number.isFinite(max))return(min+max)/2}const normalized=Number(value);return Number.isFinite(normalized)?normalized:fallback};
const stepProgress=(time,step)=>clamp((time-asNumber(step.start)-asNumber(step.delay))/Math.max(1,asNumber(step.duration,1)));
const seedRandom=seed=>{let value=(Number(seed)||1)>>>0;return()=>((value=Math.imul(1664525,value)+1013904223>>>0)/4294967296)};

export async function loadEnemyVanishCatalog(url="data/vanish-effects.json"){
  try{const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);setEnemyVanishCatalog(await response.json());return true}catch{return false}
}
export function setEnemyVanishCatalog(value){if(!value||typeof value!=="object")return false;catalog={format:"NDA_VANISH_EFFECTS",version:1,defaults:{...BUILTIN_DEFAULTS,...(value.defaults||{})},effects:{vanish_default:BUILTIN_EFFECT,...(value.effects||{})}};return true}
export function resolveEnemyVanishEffectId(enemy){const own=String(enemy?.vanishEffect||"").trim();if(own&&catalog.effects[own])return own;if(enemy?.isBoss&&catalog.effects[catalog.defaults.boss])return catalog.defaults.boss;const race=String(enemy?.enemyType||enemy?.category||enemy?.race||"normal").toLowerCase(),fallback=catalog.defaults[race]||catalog.defaults.normal||"vanish_default";return catalog.effects[fallback]?fallback:"vanish_default"}
export function getEnemyVanishEffect(enemy){return catalog.effects[resolveEnemyVanishEffectId(enemy)]||BUILTIN_EFFECT}
export function getEnemyVanishCatalog(){return structuredClone(catalog)}
export function createEnemyVanishPlayback(enemy){const effect=getEnemyVanishEffect(enemy);return Object.freeze({enemyId:String(enemy?.id||""),effectId:effect.id,duration:Math.max(1,Math.round(asNumber(effect.duration,650))),deathConfirmed:true,rewardHandled:false})}
export function markEnemyVanishPending(image){const host=image?.closest?.(".battle-enemy-member, .battle-enemy-stage");if(host)host.dataset.vanishPending="true"}
export function isEnemyVanishPending(host){return host?.dataset?.vanishPending==="true"||host?.dataset?.vanishPlaying==="true"}

export async function playEnemyVanish({image,enemy,reducedMotion=globalThis.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches}={}){
  if(!image?.isConnected||!image.complete||!image.naturalWidth)return createEnemyVanishPlayback(enemy);const effect=getEnemyVanishEffect(enemy),host=image.closest(".battle-enemy-member, .battle-enemy-stage")||image.parentElement;if(!host)return createEnemyVanishPlayback(enemy);host.dataset.vanishPending="false";host.dataset.vanishPlaying="true";const previousPosition=getComputedStyle(host).position;if(previousPosition==="static")host.style.position="relative";const canvas=document.createElement("canvas"),rect=image.getBoundingClientRect(),hostRect=host.getBoundingClientRect(),ratio=Math.min(2,globalThis.devicePixelRatio||1),width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));canvas.width=width;canvas.height=height;canvas.className="battle-enemy-vanish-canvas";Object.assign(canvas.style,{left:`${rect.left-hostRect.left}px`,top:`${rect.top-hostRect.top}px`,width:`${rect.width}px`,height:`${rect.height}px`});host.append(canvas);image.style.visibility="hidden";const controller={canvas,host,image,cancelled:false};activePlaybacks.add(controller);const duration=reducedMotion?120:Math.max(1,Math.round(asNumber(effect.duration,650)));await new Promise(resolve=>{const started=performance.now(),tick=now=>{const elapsed=Math.min(duration,now-started);drawEffectFrame(canvas,image,effect,reducedMotion?elapsed/duration*asNumber(effect.duration,650):elapsed);if(controller.cancelled||elapsed>=duration){resolve();return}controller.frame=requestAnimationFrame(tick)};controller.frame=requestAnimationFrame(tick)});cleanupPlayback(controller,previousPosition,false);return createEnemyVanishPlayback(enemy)
}
export function resetEnemyVanishEffects(root=document){for(const playback of [...activePlaybacks])if(!root||root.contains?.(playback.canvas))cleanupPlayback(playback,"",true);root?.querySelectorAll?.("[data-vanish-pending], [data-vanish-playing]").forEach(node=>{delete node.dataset.vanishPending;delete node.dataset.vanishPlaying});root?.querySelectorAll?.(".battle-enemy-member-image, #battleEnemyImage").forEach(image=>{image.style.visibility=""})}
function cleanupPlayback(playback,previousPosition,restoreImage=true){playback.cancelled=true;cancelAnimationFrame(playback.frame);playback.canvas.remove();if(restoreImage&&playback.image?.isConnected)playback.image.style.visibility="";delete playback.host?.dataset.vanishPending;delete playback.host?.dataset.vanishPlaying;if(previousPosition==="static"&&playback.host?.isConnected)playback.host.style.position="";activePlaybacks.delete(playback)}
function drawEffectFrame(canvas,image,effect,time){const g=canvas.getContext("2d"),w=canvas.width,h=canvas.height,steps=(effect.steps||[]).filter(step=>step.enabled!==false),rng=seedRandom(effect.seed),state={opacity:1,dx:0,dy:0,scaleX:1,scaleY:1,blur:0,flash:[],mask:null,fragments:null,slice:null,particles:[]};for(const step of steps){if(time<asNumber(step.start)+asNumber(step.delay))continue;const p=stepProgress(time,step);switch(step.type){case"fade":case"soft_fade":state.opacity*=asNumber(step.from,1)+(asNumber(step.to,0)-asNumber(step.from,1))*p;if(step.type==="soft_fade")state.blur+=asNumber(step.blur)*p;break;case"sink":state.dy+=asNumber(step.distance,160)*p;state.opacity*=1-p;break;case"evaporate":state.dy-=asNumber(step.distance,150)*p;state.opacity*=1-p;state.blur+=asNumber(step.blur,8)*p;state.particles.push([step,p]);break;case"collapse":state.scaleY*=1-p;state.dy+=h*p*.5;break;case"shake":state.dx+=Math.sin(time/1000*asNumber(step.frequency,24)*Math.PI*2)*asNumber(step.strength,8)*(1-p);break;case"flash":case"custom":case"boss_vanish":state.flash.push([step,p]);if(step.type==="boss_vanish")state.particles.push([step,p]);break;case"dissolve":case"burn":case"ash":case"pixelate":state.mask=[step,p];if(step.type!=="dissolve"&&step.type!=="pixelate")state.particles.push([step,p]);break;case"shatter":case"explode":state.fragments=[step,p];break;case"slice":state.slice=[step,p];break;}}
 g.clearRect(0,0,w,h);g.save();g.globalAlpha=clamp(state.opacity);g.filter=state.blur?`blur(${state.blur}px)`:"none";g.translate(w/2+state.dx,h/2+state.dy);g.scale(state.scaleX,state.scaleY);g.translate(-w/2,-h/2);if(state.fragments)drawFragments(g,image,w,h,...state.fragments,rng);else if(state.slice)drawSlice(g,image,w,h,...state.slice);else if(state.mask)drawMask(g,canvas,image,w,h,...state.mask,effect.seed);else drawContain(g,image,w,h);g.restore();for(const[step,p]of state.flash){g.save();g.globalAlpha=Math.sin(Math.PI*p)*clamp(asNumber(step.strength,1));g.globalCompositeOperation="source-atop";g.fillStyle=step.color||"#fff";g.fillRect(0,0,w,h);g.restore()}for(const[step,p]of state.particles)drawParticles(g,w,h,step,p,rng)
}
function containRect(image,w,h){const scale=Math.min(w/image.naturalWidth,h/image.naturalHeight);return{x:(w-image.naturalWidth*scale)/2,y:(h-image.naturalHeight*scale)/2,w:image.naturalWidth*scale,h:image.naturalHeight*scale}}
function drawContain(g,image,w,h){const r=containRect(image,w,h);g.drawImage(image,r.x,r.y,r.w,r.h)}
function drawSlice(g,image,w,h,step,p){const r=containRect(image,w,h),angle=asNumber(step.angle,-18)*Math.PI/180,t=Math.tan(angle),move=Math.min(1,p*4),gap=asNumber(step.gap,3);for(const upper of[true,false]){g.save();g.beginPath();if(upper){g.moveTo(r.x,r.y);g.lineTo(r.x+r.w,r.y);g.lineTo(r.x+r.w,r.y+r.h/2+t*r.w/2);g.lineTo(r.x,r.y+r.h/2-t*r.w/2)}else{g.moveTo(r.x,r.y+r.h/2-t*r.w/2);g.lineTo(r.x+r.w,r.y+r.h/2+t*r.w/2);g.lineTo(r.x+r.w,r.y+r.h);g.lineTo(r.x,r.y+r.h)}g.clip();const ox=asNumber(upper?step.upperOffsetX:step.lowerOffsetX)*(move),oy=(asNumber(upper?step.upperOffsetY:step.lowerOffsetY)+(upper?-gap/2:gap/2))*move;g.drawImage(image,r.x+ox,r.y+oy,r.w,r.h);g.restore()}}
function drawFragments(g,image,w,h,step,p,rng){const r=containRect(image,w,h),count=Math.min(80,Math.max(4,Math.round(asNumber(step.fragmentCount,24)))),cols=Math.ceil(Math.sqrt(count*r.w/r.h)),rows=Math.ceil(count/cols),fw=r.w/cols,fh=r.h/rows,spread=asNumber(step.spread,90),gravity=asNumber(step.gravity,100),rotation=asNumber(step.rotation,18)*Math.PI/180;for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const vx=(rng()-.5)*spread,vy=(rng()-.65)*spread,cx=r.x+col*fw,cy=r.y+row*fh;g.save();g.globalAlpha=1-p;g.translate(cx+fw/2+vx*p,cy+fh/2+vy*p+gravity*p*p);g.rotate((rng()-.5)*rotation*p);g.drawImage(image,col/cols*image.naturalWidth,row/rows*image.naturalHeight,image.naturalWidth/cols,image.naturalHeight/rows,-fw/2,-fh/2,fw+.5,fh+.5);g.restore()}}
function drawMask(g,canvas,image,w,h,step,p,seed){let temp=maskBuffers.get(canvas);if(!temp){temp=document.createElement("canvas");maskBuffers.set(canvas,temp)}if(temp.width!==w||temp.height!==h){temp.width=w;temp.height=h}const t=temp.getContext("2d",{willReadFrequently:true});t.clearRect(0,0,w,h);drawContain(t,image,w,h);const data=t.getImageData(0,0,w,h),pixels=data.data,dir=step.direction||"random",edge=asNumber(step.edgeGlowWidth||step.edgeWidth,0)/Math.max(w,h),color=parseColor(step.edgeGlowColor||step.edgeColor||"#fff"),pixel=Math.max(1,asNumber(step.pixelSize,1));for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;if(!pixels[i+3])continue;const qx=Math.floor(x/pixel)*pixel,qy=Math.floor(y/pixel)*pixel,n=Math.abs((Math.sin(qx*12.9898+qy*78.233+seed*37.7)*43758.5453)%1),axis=dir==="topToBottom"?y/h:dir==="bottomToTop"?1-y/h:dir==="leftToRight"?x/w:dir==="rightToLeft"?1-x/w:n;if(axis<p)pixels[i+3]=0;else if(edge&&axis<p+edge*5){pixels[i]=color[0];pixels[i+1]=color[1];pixels[i+2]=color[2]}}t.putImageData(data,0,0);g.drawImage(temp,0,0)}
function drawParticles(g,w,h,step,p,rng){const count=Math.min(100,Math.max(0,Math.round(asNumber(step.particleCount,30)))),size=asNumber(step.particleSize,3),spread=asNumber(step.spread,40),velocity=asNumber(step.velocity,45),gravity=asNumber(step.gravity,-10);g.save();g.fillStyle=step.color||step.edgeColor||"#d5dde0";for(let i=0;i<count;i++){const angle=rng()*Math.PI*2,v=velocity*(.3+rng()),x=w/2+(rng()-.5)*spread+Math.cos(angle)*v*p,y=h/2+(rng()-.5)*spread+Math.sin(angle)*v*p+gravity*p*p;g.globalAlpha=(1-p)*(.3+rng()*.7);g.fillRect(x,y,size*(.5+rng()),size*(.5+rng()))}g.restore()}
function parseColor(value){const raw=String(value).replace("#","").padEnd(6,"f");return[parseInt(raw.slice(0,2),16)||255,parseInt(raw.slice(2,4),16)||255,parseInt(raw.slice(4,6),16)||255]}

void loadEnemyVanishCatalog();
