import test from 'node:test';
import assert from 'node:assert/strict';
import {createInitialCharacter,normalizeCharacter} from '../data/classes.js';
import {getItem,getShopItemIdsForCharacter} from '../data/items.js';
import {grantItem} from '../data/inventory.js';
import {resolveFieldItemUse} from '../combat/resolve-item-use.js';
import {createBattleState,resolveBattleRound} from '../combat/battle-engine.js';
function hero(){const c=createInitialCharacter({name:'QA',job:'mage'});c.maxHp=200;c.wingGiftBaseMaxHp=200;c.hp=200;c.maxSp=101;c.sp=0;c.inventory=grantItem(c.inventory,'wing_gift',10).inventory;return c;}
test('wing gift shop opens at B80, price is 10000',()=>{assert.equal(getShopItemIdsForCharacter({highestDungeonDepthReached:79}).includes('wing_gift'),false);assert.equal(getShopItemIdsForCharacter({highestDungeonDepthReached:80}).includes('wing_gift'),true);assert.equal(getItem('wing_gift').buyPrice,10000);});
test('field use subtracts fixed base fifths and rejects fifth use or full SP without consumption',()=>{let c=hero();for(const max of [160,120,80,40]){c.sp=0;const r=resolveFieldItemUse({character:c,itemId:'wing_gift'});assert.equal(r.accepted,true);c=r.character;assert.equal(c.maxHp,max);assert.equal(c.hp,max);assert.equal(c.sp,51);}assert.equal(resolveFieldItemUse({character:c,itemId:'wing_gift'}).reason,'wingGiftLimit');const fresh=hero();fresh.sp=fresh.maxSp;assert.equal(resolveFieldItemUse({character:fresh,itemId:'wing_gift'}).reason,'fullSp');assert.equal(fresh.inventory.counts.wing_gift,10);assert.equal(resolveFieldItemUse({character:hero(),itemId:'wing_gift',context:'town'}).accepted,false);});
test('normalization and JSON reload retain penalty without compounding',()=>{let c=normalizeCharacter(createInitialCharacter({name:'QA',job:'mage'}));const base=c.maxHp;c.wingGiftUses=2;c=normalizeCharacter(c);assert.equal(c.maxHp,Math.floor(base*3/5));for(let i=0;i<3;i++)c=normalizeCharacter(JSON.parse(JSON.stringify(c)));assert.equal(c.maxHp,Math.floor(base*3/5));c.wingGiftUses=0;c=normalizeCharacter(c);assert.equal(c.maxHp,base);});
test('battle item consumes one, recovers SP and retains reduced max HP',()=>{const enemy={id:'dummy',name:'dummy',hp:9999,maxHp:9999,stats:{str:1,int:1,agi:1,dex:1,luc:1},actions:[{weight:1,action:{id:'wait',actionType:'wait'}}]};const r=resolveBattleRound({battle:createBattleState({character:hero(),enemy}),playerCommand:{type:'item',itemId:'wing_gift'},rng:()=>0});assert.equal(r.accepted,true);assert.equal(r.battle.player.maxHp,160);assert.equal(r.battle.player.hp,160);assert.equal(r.battle.player.wingGiftUses,1);assert.equal(r.battle.player.sp,51);assert.equal(r.battle.player.inventory.counts.wing_gift,9);});
