export const COMMON_CARDS = Object.freeze({
  commonStrengthUp: Object.freeze({
    id: "common_strength_up",
    rarity: "C",
    cost: 1,
    name: "Strength Up",
    footerText: "STR +1",
    nameJa: "腕力上昇",
    concept: "STR+1",
    category: "ability",
    iconId: "strength",
    effectId: "strength_up",
    maxCopies: 6,
    version: 2,
  }),
  commonKnowledgeBook: Object.freeze({
    id: "common_knowledge_book",
    rarity: "C",
    cost: 1,
    name: "Knowledge Book",
    footerText: "INT +1",
    nameJa: "知識の書",
    concept: "INT+1",
    category: "ability",
    iconId: "knowledge",
    effectId: "intelligence_up",
    maxCopies: 6,
    version: 2,
  }),
  commonLuckyCharm: Object.freeze({
    id: "common_lucky_charm",
    rarity: "C",
    cost: 1,
    name: "Lucky Charm",
    footerText: "LUC +1",
    nameJa: "幸運のお守り",
    concept: "LUC+1",
    category: "ability",
    iconId: "luck",
    effectId: "luck_up",
    maxCopies: 6,
    version: 2,
  }),
});
